// Generated by gencpp from file bot/BotPose.msg
// DO NOT EDIT!


#ifndef BOT_MESSAGE_BOTPOSE_H
#define BOT_MESSAGE_BOTPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bot
{
template <class ContainerAllocator>
struct BotPose_
{
  typedef BotPose_<ContainerAllocator> Type;

  BotPose_()
    : x(0.0)
    , y(0.0)
    , direction()  {
    }
  BotPose_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , direction(_alloc)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::bot::BotPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bot::BotPose_<ContainerAllocator> const> ConstPtr;

}; // struct BotPose_

typedef ::bot::BotPose_<std::allocator<void> > BotPose;

typedef boost::shared_ptr< ::bot::BotPose > BotPosePtr;
typedef boost::shared_ptr< ::bot::BotPose const> BotPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bot::BotPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bot::BotPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bot::BotPose_<ContainerAllocator1> & lhs, const ::bot::BotPose_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bot::BotPose_<ContainerAllocator1> & lhs, const ::bot::BotPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bot::BotPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bot::BotPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bot::BotPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bot::BotPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot::BotPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot::BotPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bot::BotPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9fe0bb04457256f44c3856c153b539c2";
  }

  static const char* value(const ::bot::BotPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9fe0bb04457256f4ULL;
  static const uint64_t static_value2 = 0x4c3856c153b539c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::bot::BotPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bot/BotPose";
  }

  static const char* value(const ::bot::BotPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bot::BotPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"string direction\n"
;
  }

  static const char* value(const ::bot::BotPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bot::BotPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BotPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bot::BotPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bot::BotPose_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOT_MESSAGE_BOTPOSE_H
